#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_split_4x6_5(KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_F11, KC_TAB, KC_Q, KC_W, KC_F, KC_D, KC_K, KC_J, KC_U, KC_R, KC_L, KC_SCLN, KC_BSLS, KC_LSPO, KC_A, KC_S, KC_E, KC_T, KC_G, KC_Y, KC_N, KC_I, KC_O, KC_H, KC_RSPC, MO(3), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_P, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_LGUI, KC_LALT, KC_SPC, KC_LCTL, KC_RCTL, KC_ENT, KC_QUOT, KC_BSPC, LT(1,KC_ESC), LT(2,KC_F1), KC_TILD),
	[1] = LAYOUT_split_4x6_5(KC_TRNS, RGB_SPD, RGB_SPI, KC_F3, LALT(KC_F4), RGB_M_SN, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_HUD, RGB_HUI, RGB_RMOD, RGB_MOD, RGB_M_B, KC_TRNS, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, KC_TRNS, KC_TRNS, RGB_SAD, RGB_SAI, RGB_VAD, RGB_VAI, RGB_M_G, KC_TILD, KC_UNDS, KC_MINS, KC_PLUS, KC_EQL, KC_TRNS, RGB_TOG, KC_WSCH, KC_MYCM, KC_CALC, KC_MAIL, KC_WHOM, KC_TRNS, KC_LEFT, KC_UP, KC_DOWN, KC_RGHT, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_F5, LSFT(KC_QUOT), KC_TRNS, KC_TRNS, KC_PGUP, KC_PGDN),
	[2] = LAYOUT_split_4x6_5(KC_F12, KC_F1, KC_F2, KC_BTN3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_TRNS, KC_TRNS, KC_BTN1, KC_MS_U, KC_BTN2, KC_TRNS, KC_TRNS, KC_TRNS, KC_WH_U, KC_INS, KC_TRNS, KC_MUTE, KC_TRNS, MACRO_1, KC_MS_L, KC_MS_D, KC_MS_R, KC_TRNS, KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_R, KC_MPLY, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MACRO_0, KC_TRNS, KC_TRNS, KC_PSCR, LAG(KC_LEFT), KC_VOLU, KC_VOLD, LAG(KC_RGHT), KC_TRNS, KC_HOME, KC_BSPC, KC_END, KC_TRNS, KC_TRNS, QK_BOOT, KC_TRNS, KC_DEL, KC_TRNS, KC_TRNS),
	[3] = LAYOUT_split_4x6_5(KC_NO, LCA(KC_F1), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_7, KC_8, KC_9, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_4, KC_5, KC_6, KC_NO, KC_NO, KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_1, KC_2, KC_3, KC_DOT, TO(4), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_0, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS),
	[4] = LAYOUT_split_4x6_5(KC_NO, KC_5, KC_1, KC_2, KC_3, KC_4, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_J, KC_U, KC_R, KC_L, KC_NO, KC_NO, KC_G, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_Y, KC_N, KC_I, KC_O, KC_H, KC_NO, KC_RCTL, KC_T, KC_Z, KC_X, KC_C, KC_V, KC_NO, KC_NO, KC_COMM, KC_DOT, KC_SLSH, KC_TRNS, KC_LALT, KC_SPC, KC_LCTL, TO(0), KC_TRNS, KC_TRNS, KC_BSPC, KC_ESC, KC_TRNS, KC_TRNS)
};


// bool process_record_user(uint16_t keycode, keyrecord_t *record) {
//     if (record->event.pressed) {
//         switch (keycode) {
//             case MACRO_0:
//                 SEND_STRING(SS_TAP(X_QUOT)SS_TAP(X_C));
//                 return false;
//             case MACRO_1:
//                 SEND_STRING(SS_DOWN(X_RSFT)SS_TAP(X_GRV)SS_UP(X_RSFT)SS_TAP(X_A));
//                 return false;
//         }
//     }
//
//     return true;
// };
HSV current_color;
HSV initial_color = {253, 212, 255};

layer_state_t layer_state_set_user(layer_state_t state) {
	switch (get_highest_layer(state)) {
		case 0:
			rgb_matrix_sethsv_noeeprom(initial_color.h, initial_color.s, current_color.v);
			break;
		case 1:
			current_color = rgb_matrix_get_hsv();

			rgb_matrix_sethsv_noeeprom(0, 255, current_color.v);
			break;
		case 2:
			current_color = rgb_matrix_get_hsv();

			//h 255 is 360
			rgb_matrix_sethsv_noeeprom(244, 170, current_color.v);
			break;
		case 3:
			current_color = rgb_matrix_get_hsv();

			rgb_matrix_sethsv_noeeprom(229, 241, current_color.v);
			break;
		case 4:
			current_color = rgb_matrix_get_hsv();

			rgb_matrix_sethsv_noeeprom(140, 255, current_color.v);
			break;
		default:
			rgb_matrix_sethsv_noeeprom(initial_color.h, initial_color.s, current_color.v);
			break;
	}
	return state;
}

void keyboard_post_init_user(void) {
	// HSV initial_color = rgb_matrix_get_hsv();

  // Call the post init code.
  rgb_matrix_sethsv(initial_color.h, initial_color.s, initial_color.v);
}

// void suspend_power_down_user(void) {
//   rgb_matrix_sethsv_noeeprom(0, 0, 0);
// 	// rgb_matrix_set_suspend_state(true);
// }

// void suspend_wakeup_init_user(void) {
// 	rgb_matrix_sethsv(253, 212, current_color.v);
//   // rgb_matrix_set_suspend_state(false);
// }

// void suspend_power_down_keymap(void) {
// 	rgb_matrix_set_suspend_state(true);
//   rgb_matrix_sethsv(0, 0, 0);
// }

// void suspend_wakeup_init_keymap(void) {
// 	rgb_matrix_set_suspend_state(false);
//   rgb_matrix_sethsv(0, 0, 0);
// }
