# Space saving settings.
TAP_DANCE_ENABLE = no
QMK_SETTINGS = no
LTO_ENABLE = yes
COMBO_ENABLE = yes
KEY_OVERRIDE_ENABLE = no
MOUSEKEY_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes
VIALRGB_ENABLE = yes
CAPS_WORD_ENABLE = yes
